### ISSUE TITLE
Cant install payroll in odoo 15

### ISSUE THREAD

**Issue by felixgonsug** [OCA/payroll#115]
When trying to install, i get a server error and a traceback with this message at the bottom

`ImportError: cannot import name 'hr_salary_rule' from partially initialized module 'odoo.addons.payroll.models' (most likely due to a circular import) (/mnt/extra-addons/payroll/models/__init__.py)`

**Comment by nimarosa** [comment]
Hello, the problem it's on your end. Payroll installs okay in v15.0. Maybe you added the module twice or something in your instance. Checked in runboat and locally and installation works okay.

Please check your instance.

**Comment by felixgonsug** [comment]
Ok, my version of server is the oficial docker one. Any sugestion to debug this issue?
