### ISSUE TITLE
payroll_account with accounting fields as company_dependent fields

### ISSUE THREAD

**Issue by unique4** [OCA/payroll#116]
Currently accounting fields in salary rules are not company_dependent. The accounting in Salary rules should behave as Product, Product Categories, Partner, ...

Odoo (v11) has actually fixed this: [https://github.com/odoo/odoo/pull/28675](https://github.com/odoo/odoo/pull/28675) 
Related issue: [https://github.com/odoo/odoo/issues/23814](https://github.com/odoo/odoo/issues/23814)

**Comment by unique4** [comment]
@nimarosa Hi, did you closed this Issue by mistake?

**Comment by nimarosa** [comment]
> @nimarosa Hi, did you closed this Issue by mistake?

Yea I thought it was another issue. Opened again.
