### ISSUE TITLE
holiday.holiday_status_id.name => holiday.holiday_status_id.code - should be code, not name

### ISSUE THREAD

**Issue by vbezl** [OCA/payroll#12]
https://github.com/OCA/payroll/blob/b88a195d92286f2ad3f7c88144fd048225df9175/payroll/models/hr_payslip.py#L353

Please change to:
"code": holiday.holiday_status_id.**code** or "GLOBAL",

**Comment by nimarosa** [comment]
Refer to #14 pull request fixes the problem.

**Comment by nimarosa** [comment]
#27 Fixed in 14.0 branch

**Comment by nimarosa** [comment]
**We can close this issue the issue it's resolved in the 14.0 branch. Can be downgraded easily to other versions. **
