### ISSUE TITLE
Wizard view error hr_payslips_by_employee.xml

### ISSUE THREAD

**Issue by birok** [OCA/payroll#141]
## Module
payroll

## Describe the bug
view to add employees is not complete in payroll processing

## To Reproduce
In payroll, enter the payroll processing, create a new one and use the button to add employees
**Affected versions**: 16.0

**Expected behavior**
1. Enter the payroll processing
2. Create a new record
3. Use the button to add employees

**Additional context**

**Comment by nimarosa** [comment]
Can you elaborate about this? I tested and i can add employees without problem.
