### ISSUE TITLE
Regression in behaviour of payroll module Worked Days Lines leave calculation

### ISSUE THREAD

**Issue by mtelahun** [OCA/payroll#38]
CC'ing developers involved in change
@nimarosa  @pedrobaeza  @apps2grow 

## Module
payroll

## Describe the bug
Hi guys, this change happened a few months ago but I only noticed it now when I updated my upstream sources and my unit tests started to fail.

PR #27 changed the sign of calculated hours and days of leaves to be negative. This is causing unit tests in my custom modules to fail.
I don't think the previous behavior was a bug, and even if it was I believe it's a bit late in the 14.0 life-cycle to be changing expected behavior now. Basically, this gratuitously changes previous behavior of the module without any tangible benefits to the wider community.

**Expected behavior**
That the module continues to function as it has before.

**Comment by mtelahun** [comment]
I forgot to mention. I also have the same problem with the payroll data that has now become demo data. This has created 2 problems for me:
1. Again, some of my unit tests depend on the data
2. I have csv files that whenever I setup a new database I either customize it for my needs or archive it
 
I understand why the change to the demo data was made, but anyone who is using the payroll module has already put in places mitigations to get around it and this change just blows all their customizations out of the water.

**Comment by nimarosa** [comment]
As stated in your PR. Not a bug. Read the PR comment for more details.

**Comment by mtelahun** [comment]
As mentioned in the PR I will create a configuration know to keep the old behaviour
