### ISSUE TITLE
[15.0] Rename "payroll" to "hr_payroll_oca"?

### ISSUE THREAD

**Issue by ghost** [OCA/payroll#49]
In https://github.com/oca/edi many module names end with "_oca" to show that it is the OCA alternative to another module with the same name. I think this is a nice convention, so I suggest to rename "payroll" to "hr_payroll_oca", and "payroll_account" to "hr_payroll_account_oca". Then in the list of modules, all payroll modules will be grouped together, starting with "hr_payroll".

What do you think?

**Comment by pedrobaeza** [comment]
This was already discussed, and the convention is only to not conflict in Odoo SA modules, which is not the case. I prefer to keep the name as is.

**Comment by nimarosa** [comment]
Yes i think this was solved when we renamed the module from hr_payroll to payroll, so it won't conflict with the enterprise version one.

**Comment by nimarosa** [comment]
I also vote for no renaming the module because it can bring problems to already running production installations.
