### ISSUE TITLE
About pending migrations

### ISSUE THREAD

**Issue by nimarosa** [OCA/payroll#78]
Hello oca/payroll users and contributors. 

This thread is to discuss migrations to v15 and v16. As you can see, the new v16 branch is now live and we still in the v14.

Since we are using v14.0 to do improvements and changes to the modules, I suggest we continue doing so until we think it's time to migrate to v15.0 and then to v16.0. 
My approach here will be maintain the tree versions because i have clients that will continue with v14.0 for a while, but i think we should start with v15.0 migration soon. 

From my end, i have some PRs that i wish to merge first in v14.0 before we start the migration so we can have this changes in following versions. I will try to include all this changes this week or the following.
If someone has something new or improvements that wish to include in the module, i suggest to do it as fast as possible.
So i think we can schedule deadline for starting migrations to other versions on 20/10/2022. 

As i said, i will continue maintaining v14.0 version but also after migration, I will port any change in any branch to the other ones, so it will be good for all of us to include any changes you wish to include before this date, so we reduce the workload of backporting versions. 

Any doubt or suggestion about migrations can also be addressed in this thread. 
Kind regards to everyone.

**Comment by TheCloneMaster** [comment]
Hi @nimarosa,
We have made a couple changes for multicompany payroll management, to allow payroll admins to create runs for employees on different companies without switching their own. Company_id is calculated from employee's own company, not from env's company default.
Also to allow analytic account from employees' contract if defined instead of rule's account.
Both are extra features, if not configured behavior doesn't change.
Do you consider them useful, to present PRs?

Regards,
-Mario

**Comment by nimarosa** [comment]
> Hi @nimarosa,
> 
> We have made a couple changes for multicompany payroll management, to allow payroll admins to create runs for employees on different companies without switching their own. Company_id is calculated from employee's own company, not from env's company default.
> 
> Also to allow analytic account from employees' contract if defined instead of rule's account.
> 
> Both are extra features, if not configured behavior doesn't change.
> 
> Do you consider them useful, to present PRs?
> 
> 
> 
> Regards,
> 
> -Mario

Hello @TheCloneMaster, yes feel free to introduce the PRs and we can review it. It looks a useful functions for businesses that use multicompany.

**Comment by mtelahun** [comment]
Odoo is now at 16.0 and we haven't yet migrated modules to 15.0. Is anyone working on this? I have an interest in moving to 16.0 soon so if no one is working on this I will propose PRs for both 15.0 and 16.0.

**Comment by pedrobaeza** [comment]
I think the migration should be pretty straight forward, isn't it? You can go ahead, and the first gets the strike.

**Comment by nimarosa** [comment]
> Odoo is now at 16.0 and we haven't yet migrated modules to 15.0. Is anyone working on this? I have an interest in moving to 16.0 soon so if no one is working on this I will propose PRs for both 15.0 and 16.0.

@mtelahun Hello. You can propose the PRs. I have interest to migrate too but it has been a very busy weeks. That's why I created this thread to acelérate and start the migrations at least by the end of the month. 

So if you want you can propose the migrations. Like @pedrobaeza said i think they will be pretty straightforward and require no code changes.

**Comment by nimarosa** [comment]
I reopened v15 issue that was stale.

**Comment by nimarosa** [comment]
Closed.
